# Generated by Django 4.0.6 on 2022-07-19 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_pedido_monto_total_alter_pedido_nro_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('1', 'Pagado'), ('0', 'Solicitado')], default='0', max_length=1),
        ),
    ]
